<!DOCTYPE html>
<html>
<head>
    <title>BladeSoulTool Issue</title>
    <link href="../../bower_components/bootstrap/dist/css/bootstrap.min.css" type="text/css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Issues: <?php echo $issue->id ?></h3>
        </div>
    </div>
    <div ng-controller="BstSearchCtrl">
        <div class="row">
            <div class="col-md-12">
                <div class="clearfix">
                    <div style="width:100px;font-weight:bold;" class="pull-left"><span>Id</span></div>
                    <div class="pull-left"><?php echo $issue->id ?></div>
                </div>
                <div class="clearfix">
                    <div style="width:100px;font-weight:bold;" class="pull-left"><span>Origin</span></div>
                    <div class="pull-left"><pre><?php print_r(json_decode($issue->origin, true)) ?></pre></div>
                </div>
                <div class="clearfix">
                    <div style="width:100px;font-weight:bold;" class="pull-left"><span>Target</span></div>
                    <div class="pull-left"><pre><?php print_r(json_decode($issue->target, true)) ?></pre></div>
                </div>
                <div class="clearfix">
                    <div style="width:100px;font-weight:bold;" class="pull-left"><span>Console</span></div>
                    <div class="pull-left"><pre><?php echo $issue->console; ?></pre></div>
                </div>
                <div class="clearfix">
                    <div style="width:100px;font-weight:bold;" class="pull-left"><span>Solved</span></div>
                    <div class="pull-left"><?php echo $issue->solved ?></div>
                </div>
                <div class="clearfix">
                    <div style="width:100px;font-weight:bold;" class="pull-left"><span>Time</span></div>
                    <div class="pull-left"><?php echo date('Y-m-d H:i:s', $issue->time) ?></div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>